### ISSUE TITLE
common/exec task fails in start actions

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/handler#17]
**Describe the bug**
`common/exec` with inputs requires a recommendedBaseline field to be present in order to interpolate inputs. This fails in start actions, since there is no `recommendedBaseline` set in the experiment status at this stage.

The preferred bug fix is to introduce an optional `interpolate` boolean input to exec tasks (in addition to `cmd` and `args` which are currently supported). Default `interpolate` value could be true, but when set to false, exec will not attempt to interpolate inputs.

**Comment by sriumcp** [comment]
Intended to be fixed by this PR: https://github.com/iter8-tools/handler/pull/18

This issue can be closed once disableInterpolation is verified to work in a e2e test.

**Comment by kalantar** [comment]
The above PR does not seem to have fixed this problem. I am still seeing it.

**Comment by sriumcp** [comment]
Did you try the start exec task with "interpolate: false" flag?

**Comment by kalantar** [comment]
I did not. I just tried `disableInterpolation: true` and that seemed to work. I do not understand why it works this way. I would prefer not having to specify but rather have it react based on whether or not the field is present or not.

**Comment by sriumcp** [comment]
Sorry, `disableInterpolation: true` is the right flag.

Yes, automatically detecting if a placeholder is present or not would be a nice feature to have.

**Comment by sriumcp** [comment]
I am leaving this open since `disableInterpolation: true` is yet to be documented. I will close this after the doc is in for the exec task.

**Comment by sriumcp** [comment]
Done.
